export interface resultsModel{
    _id: string,
    cityid: string,
    validdateutc: string,
    winddirectioncardinal: string,
    probabilityofprecip: string,
    relativehumidity:  string,
    name: string,
    dateInsert: string,
    longitude: string,
    state: string,
    lastreporttime: string,
    skydescriptionlong: string,
    stateabbr: string,
    tempc: string,
    latitude: string,
    iconcode: string,
    windspeedkm: string,
}